
from datetime import datetime, timezone


def normalize_france_travail(offer: dict) -> dict:
    return {

    "id"    :	                            offer.get("id"),
    "title" :	                            offer.get("intitule"),
    "description" :	                        offer.get("description"),
    "creation_date" :	                    offer.get("dateCreation"),
    "update_date" :	                        offer.get("dateActualisation"),
    "workplace_label" :                     offer.get("lieuTravail", {}).get("libelle"),
    "workplace_latitude" :                  offer.get("lieuTravail", {}).get("latitude"),
    "workplace_longitude" :                 offer.get("lieuTravail", {}).get("longitude"),
    "workplace_postal_code" :               offer.get("lieuTravail", {}).get("codePostal"),
    "workplace_city" :                      offer.get("lieuTravail", {}).get("commune"),
    "rome_code"    :	                    offer.get("romeCode"),
    "rome_label"    :	                    offer.get("romeLibelle"),
    "name_label"    :	                    offer.get("appellationlibelle"),
    "company_name" :                        offer.get("entreprise", {}).get("nom"),
    "company_description" :                 offer.get("entreprise", {}).get("description"),
    "company_logo" :                        offer.get("entreprise", {}).get("logo"),
    "company_url" :                         offer.get("entreprise", {}).get("url"),
    "company_suitablecompany" :             offer.get("entreprise", {}).get("entrepriseAdaptee"),
    "contract_type" :                       offer.get("typeContrat"),
    "contract_type_label" :	                offer.get("typeContratLibelle"),
    "contract_nature" :	                    offer.get("natureContrat"),
    "required_experience" :	                offer.get("experienceExige"),
    "experience_label" :	                offer.get("experienceLibelle"),
    "trainings" :                           offer.get("formations", []),
    "salary_label" :                        offer.get("salaire", {}).get("libelle"),
    "salary_comment" :                      offer.get("salaire", {}).get("commentaire"),
    "salary_supplement1" :                  offer.get("salaire", {}).get("complément1"),
    "salary_supplement2" :                  offer.get("salaire", {}).get("complément2"),
    "salary_list_of_supplements" :          offer.get("salaire", {}).get("listeComplements",[]),
    "work_duration_label" :	                offer.get("dureeTravailLibelle"),
    "work_duration_label_converted" :	    offer.get("dureeTravailLibelleConverti"),
    "apprenticeship" :	                    offer.get("alternance"),
    "contact_name" :                        offer.get("contact", {}).get("nom"),
    "contact_coordinates1" :                offer.get("contact", {}).get("coordonnees1"),
    "contact_coordinates2" :                offer.get("contact", {}).get("coordonnees2"),
    "contact_coordinates3" :                offer.get("contact", {}).get("coordonnees3"),
    "contact_phone" :                       offer.get("contact", {}).get("telephone"),
    "contact_email" :                       offer.get("contact", {}).get("courriel"),
    "contact_comment" :                     offer.get("contact", {}).get("commentaire"),
    "recruiter_url" :                       offer.get("contact", {}).get("urlRecruteur"),
    "application_url" :                     offer.get("contact", {}).get("urlPostulation"),
    "agency_phone" :                        offer.get("agence", {}).get("telephone"),
    "agency_email" :                        offer.get("agence", {}).get("courriel"),
    "number_of_positions" :	                offer.get("nombrePostes"),
    "accessible_th" :	                    offer.get("accessibleTH"),
    "qualification_code" :	                offer.get("qualificationCode"),
    "qualification_label" :	                offer.get("qualificationLibelle"),
    "naf_code" :	                        offer.get("codeNAF"),
    "sector_activity" :	                    offer.get("secteurActivite"),
    "sector_activity_label" :	            offer.get("secteurActiviteLibelle"),
    "employee_breakage_establishment" :	    offer.get("trancheEffectifEtab"),
    "offer_origin":                         offer.get("origineOffre", {}).get("origine"),
    "offers_missing_candidates" :	        offer.get("offresManqueCandidats"),
    "adapted_company" :	                    offer.get("entrepriseAdaptee"),
    "employer_handiengage" :	            offer.get("employeurHandiEngage"),
    "languages" :                           offer.get("langues", []),
    "competences":                          offer.get("competences", []),
    "professional_qualities" :              offer.get("qualitesProfessionnelles", []),
    "work_context_schedules" :              offer.get("contexteTravail", {}).get("horaires"),
    "work_context_exercise_conditions" :    offer.get("contexteTravail", {}).get("conditionsExercice"),
    "collected_at" :	                    datetime.now(timezone.utc).isoformat(),
    "source" :	                            "France_Travail",
        }
